ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'NATIONAL_ID';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'COMPANY_REGISTRATION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'TAX_CERTIFICATE';
